### ISSUE TITLE
Logout Requires Refresh

### ISSUE THREAD

**Issue by irmerk** [bookworm-reads/web#5]
> Logging out on web isn’t reflected everywhere until user refreshes

## Steps to Reproduce

1.
2.
3.
4.

## Context

> When user presses log out button on web on their profile, the log out button goes away but the user’s wormy still appears in the header, so it isn’t clear if the log out really worked or not. If the user navigates to the home page, they’ll see their own library details, and if they then navigate back to their profile they appear fully logged in again, with the log out button appearing again. Makes it look like logout is broken. 

> If the user refreshes the page, they appear logged out everywhere.

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

**Comment by astone123** [comment]
this was resolved with https://github.com/ameliagoodman/bookworm-web/pull/24
