### ISSUE TITLE
Infinite Spinner on Pages

### ISSUE THREAD

**Issue by irmerk** [bookworm-reads/web#8]
> Fix infinite spinner on profile and book pages on web 

## Steps to Reproduce

1.
2.
3.
4.

## Context

> There’s a spinner that doesn’t seem to go away at the bottom of profile or book page on web. Particularly noticeable for new users or books without many posts about them.

![Image](https://github.com/bookworm-reads/web/assets/36460856/5da97a2c-dbbb-4875-af0e-db4cc474df6a)

> in InfiniteScroll, need to set hasMore to false when there is no more data to load instead of leaving it at true indefinitely

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

**Comment by ameliagoodman** [comment]
fixed with https://github.com/ameliagoodman/bookworm-web/commit/830dea46378baa946ae5035d251c101a61b7a033
